runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_idle_instances: 0
  min_idle_instances: 0
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
  max_pending_latency: 5000ms
  min_pending_latency: 5000ms
env_variables:
  NODE_ENV: production
  SESSION_SECRET: your-secret-session-key
  SESSION_KEY: your-secret-session-key-value
  MONGO_SESSION_URL: your-mongodb-auth-url-for-session-data
  MONGO_APP_URL: your-mongodb-auth-url-for-app-data
  GCP_STORAGE: <Firebase-Project-Id>.appspot.com
  TEST_AUTH_KEY: some-sample-jwt-token
